# https://taskfile.dev
version: "3"

tasks:
  release:
    desc: build and publish release
    cmds:
      - test {{.CLI_ARGS}}
      - grep -F '"{{.CLI_ARGS}}"' Cargo.toml
      - cargo publish
      - git tag {{.CLI_ARGS}}
      - git push
      - git push --tags
      - gh release create --generate-notes {{.CLI_ARGS}}
      - gh release upload {{.CLI_ARGS}} main.wasm

  format:
    desc: "run code formatters"
    cmds:
      - cargo fmt
  lint:
    desc: "run linters"
    cmds:
      - cargo clippy
  test:
    desc: "run linters"
    cmds:
      - cargo test
  all:
    cmds:
      - task: format
      - task: lint
      - task: test
  default:
    - task: all
